In [21]:
import pandas as pd
import numpy as np

data={
    'Customer_name':["Asha","Bala","Chitra","Deepa","Esha","Bala","Bala","Bala"],
    'City':['Bangalore','Delhi','Mumbai','Delhi','Bangalore','Delhi','Delhi','Delhi'],
    'Order_value':[5000,7000,np.nan,6500,7200,7000,7000,7000],
    'Email':['asha123@gmail.com','bala@gmail.com','chitra@company.com','deepa_98@yahoo.com','esha@gmail.com','bala@gmail.com','bala@gmail.com','bala@gmail.com']
}

df=pd.DataFrame(data)
df

  Customer_name       City  Order_value               Email
0          Asha  Bangalore       5000.0   asha123@gmail.com
1          Bala      Delhi       7000.0      bala@gmail.com
2        Chitra     Mumbai          NaN  chitra@company.com
3         Deepa      Delhi       6500.0  deepa_98@yahoo.com
4          Esha  Bangalore       7200.0      esha@gmail.com
5          Bala      Delhi       7000.0      bala@gmail.com
6          Bala      Delhi       7000.0      bala@gmail.com
7          Bala      Delhi       7000.0      bala@gmail.com

HANDLING DUPLICATES VALUES:-
DUPLICATES OCCUR WHEN THE SAME RECORD APPEARS MULTIPLE TIMES IN A DATASET.

COMMON REASONS:
- DATA ENTRY ERRORS
- MERGING DATASETS
- SYSTEM LOGGING ERRORS

DUPLICATES CAN DISTORT THE ANALYSIS, FOR EXAMPLE:
REVENUE MAY APPEAR HIGHER THEN REALITY

In [ ]:
#Identifying duplicates
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [7]:
#Viewing duplicate rows
df[df.duplicated()]

  Customer_name   City  Order_value           Email
5          Bala  Delhi       7000.0  bala@gmail.com

In [9]:
#Removes completely identical rows
df.drop_duplicates()

  Customer_name       City  Order_value               Email
0          Asha  Bangalore       5000.0   asha123@gmail.com
1          Bala      Delhi       7000.0      bala@gmail.com
2        Chitra     Mumbai          NaN  chitra@company.com
3         Deepa      Delhi       6500.0  deepa_98@yahoo.com
4          Esha  Bangalore       7200.0      esha@gmail.com

In [12]:
#using subset

df.drop_duplicates(subset='Email')
#this removes duplicates only based on the Email column

  Customer_name       City  Order_value               Email
0          Asha  Bangalore       5000.0   asha123@gmail.com
1          Bala      Delhi       7000.0      bala@gmail.com
3         Deepa      Delhi       6500.0  deepa_98@yahoo.com
4          Esha  Bangalore       7200.0      esha@gmail.com

In [ ]:
#Keep decides with duplicate record remains
df.drop_duplicates(keep='first')
#keeps the first duplicate record

  Customer_name       City  Order_value               Email
0          Asha  Bangalore       5000.0   asha123@gmail.com
1          Bala      Delhi       7000.0      bala@gmail.com
2        Chitra     Mumbai          NaN      bala@gmail.com
3         Deepa      Delhi       6500.0  deepa_98@yahoo.com
4          Esha  Bangalore       7200.0      esha@gmail.com

In [ ]:
df.drop_duplicates(keep='last')
#Keeps the last duplicate record

  Customer_name       City  Order_value               Email
0          Asha  Bangalore       5000.0   asha123@gmail.com
2        Chitra     Mumbai          NaN      bala@gmail.com
3         Deepa      Delhi       6500.0  deepa_98@yahoo.com
4          Esha  Bangalore       7200.0      esha@gmail.com
7          Bala      Delhi       7000.0      bala@gmail.com

In [ ]:
df.drop_duplicates(keep=False)
#Keep parameter accepts only 3 values- first, last, false

  Customer_name       City  Order_value               Email
0          Asha  Bangalore       5000.0   asha123@gmail.com
2        Chitra     Mumbai          NaN      bala@gmail.com
3         Deepa      Delhi       6500.0  deepa_98@yahoo.com
4          Esha  Bangalore       7200.0      esha@gmail.com

In [19]:
#STRING OPERATIONS WITH .str

#TEXT COLUMNS IN PANDAS CAN USE THE .str ACCESSOR WHICH ALLOWS VECTORIZED STRING OPERATIONS

df['City'].str.lower()

0    bangalore
1        delhi
2       mumbai
3        delhi
4    bangalore
5        delhi
6        delhi
7        delhi
Name: City, dtype: str

In [22]:
df[df['Email'].str.contains('gmail')]

  Customer_name       City  Order_value              Email
0          Asha  Bangalore       5000.0  asha123@gmail.com
1          Bala      Delhi       7000.0     bala@gmail.com
4          Esha  Bangalore       7200.0     esha@gmail.com
5          Bala      Delhi       7000.0     bala@gmail.com
6          Bala      Delhi       7000.0     bala@gmail.com
7          Bala      Delhi       7000.0     bala@gmail.com

In [23]:
#Removes extra spaces - usefull when data comes from forms or excel sheets
df['Customer_name'].str.strip()

0      Asha
1      Bala
2    Chitra
3     Deepa
4      Esha
5      Bala
6      Bala
7      Bala
Name: Customer_name, dtype: str

In [24]:
df['Email'].str.replace('gmail.com','gmail.co')

0      asha123@gmail.co
1         bala@gmail.co
2    chitra@company.com
3    deepa_98@yahoo.com
4         esha@gmail.co
5         bala@gmail.co
6         bala@gmail.co
7         bala@gmail.co
Name: Email, dtype: str

In [26]:
df[df['Email'].str.startswith('a')]

  Customer_name       City  Order_value              Email
0          Asha  Bangalore       5000.0  asha123@gmail.com

In [28]:
df['Email'].str.split("@")

0     [asha123, gmail.com]
1        [bala, gmail.com]
2    [chitra, company.com]
3    [deepa_98, yahoo.com]
4        [esha, gmail.com]
5        [bala, gmail.com]
6        [bala, gmail.com]
7        [bala, gmail.com]
Name: Email, dtype: object

In [30]:
df['Greeting']="Hello"+" "+df['Customer_name']
print(df['Greeting'])

0      Hello Asha
1      Hello Bala
2    Hello Chitra
3     Hello Deepa
4      Hello Esha
5      Hello Bala
6      Hello Bala
7      Hello Bala
Name: Greeting, dtype: str

Regex - Regular Expressions

TO EXTRACT PATTERNS FROM THE TEXT

COMMON REGEX PATTERNS-

\d -  DIGIT
\w - LETTER OR NUMBER
^  - START OF A STRING
$  - END OF A STRING
.  - ANY CHARACTER
+  - ONE OR MORE
*  - ZERO OR MORE


COMMONLY USED WITH -

.str.constains()
.str.extract()
.str.replace()
.str.match()

In [11]:
import pandas as pd

data={"Email":["Asha123@gmail.com",
              "Bala@gmail.com",
              "Chitra@company.com",
              "Deepa_98@yahoo.com"]}

df=pd.DataFrame(data)

In [2]:
# extract numbers from text
df["Email"].str.extract(r"(\d+)")

     0
0  123
1  NaN
2  NaN
3   98

In [3]:
#FIND ROWS CONTAINING NUMBERS
df["Email"].str.contains(r"\d")

0     True
1    False
2    False
3     True
Name: Email, dtype: bool

In [4]:
#EXTRACT EMAIL DOMAIN
df["Email"].str.extract(r"@(\w+)")

         0
0    gmail
1    gmail
2  company
3    yahoo

WHEN WE WRITE @(\w+) :-

() - CAPTURE GROUP
\w - LETTER OR NUMBER
+  -  ONE OR MORE

HERE MATCH STARTS AT THE SYMBOL @ BUT SINCE @ IS OUTSIDE OF THE CAPTURE GROUP IT IS NOT EXTRACTED
SO ONLY WHAT IS INSIDE THE CAPTURE GROUP() IS EXTRACTED.

In [ ]:
#FIND EMAILS ENDING WITH gmail.com
df["Email"].str.contains(r"@gmail\.com$")

0     True
1     True
2    False
3    False
Name: Email, dtype: bool

In [8]:
data={"Name":["Asha","Bala","Charlie","Deepak"]}
df=pd.DataFrame(data)

In [9]:
#FIND NAMES STARTING WITH A
df["Name"].str.contains(r"^A")

0     True
1    False
2    False
3    False
Name: Name, dtype: bool

In [18]:
#REMOVE NUMBERS FROM EMAILS
df["Email"].str.replace(r"\d","",regex=True)

0        Asha@gmail.com
1        Bala@gmail.com
2    Chitra@company.com
3      Deepa_@yahoo.com
Name: Email, dtype: str

In [19]:
#REGEX GROUPS
#Deepa_98@gmail.com
#WE WANT TO EXTRACT BOTH NAME & NUMBER IN THE EMIAL SEPARATELY

df["Email"].str.extract(r"(\w+)_(\d+)")

       0    1
0    NaN  NaN
1    NaN  NaN
2    NaN  NaN
3  Deepa   98