DATA TRANSFORMATION :-

.map() - REPLACES VALUES USING A DICTIONARY MAPPING

MAP IN PANDS IS USED TO TRANSFORM OR SUBSTITUTE VALUES IN A SINGLE COLUMN(SERIES) USING A MAPPING RULE.
COMMONLY USED IN DATA CLEANING OR FEATURE ENGINEERING.

SYNTAX:- series.map(mapping)


HERE MAPPING CAN BE ANOTHER:

DICTIONARY
A FUNCTION
ANOTHER SERIES

In [6]:
import pandas as pd
data={"City":
      ["Bangalore","Delhi","Mumbai"]
}
df=pd.DataFrame(data)
df

        City
0  Bangalore
1      Delhi
2     Mumbai

In [8]:
#CONVERT CITY TO REGIONS
region_map={"Bangalore":"South",
            "Delhi": "North",
            "Mumbai":"West"
            }

df["Region"]=df["City"].map(region_map)
df

        City Region
0  Bangalore  South
1      Delhi  North
2     Mumbai   West

In [11]:
#MAPPING USING A FUNCTION

#.map() - CAN APPLY A FUNCTION TO EACH VALUE

df["city_length"]=df["City"].map(len)
df

        City Region  city_length
0  Bangalore  South            9
1      Delhi  North            5
2     Mumbai   West            6

In [13]:
#MAPPING THROUGH A SERIES
city_series=pd.Series({"Bangalore":"South",
                       "Delhi":"North",
                       "Mumbai":"West"})

df["Region"]=df["City"].map(city_series)
df

        City Region  city_length
0  Bangalore  South            9
1      Delhi  North            5
2     Mumbai   West            6

In [14]:
region_map={"Bangalore":"South",
            "Delhi": "North",
            }

df["Region"]=df["City"].map(region_map)
df

        City Region  city_length
0  Bangalore  South            9
1      Delhi  North            5
2     Mumbai    NaN            6

In [16]:
#FILLING MISSING VALUES USING MAP

df["Region"]=df["City"].map(region_map).fillna("other")
df

        City Region  city_length
0  Bangalore  South            9
1      Delhi  North            5
2     Mumbai  other            6

In [12]:
import pandas as pd
import numpy as np

data={"Customer":["Asha","Bala","Charlie"],
      "Sales":[50000,30000,15000]}

df=pd.DataFrame(data)

In [14]:
#APPLYING CUSTOM FUNCTIONS
#.apply() - LETS US RUN CUSTOM LOGIC ON ROWS OR COLUMNS

#Example - classify sales performance

def sales_category(x):
    if x > 40000:
        return "High"
    elif x > 25000:
        return "Medium"
    else:
        return "Low"
    
#Apply function

df["sales_category"]=df["Sales"].apply(sales_category)
df

  Customer  Sales sales_category
0     Asha  50000           High
1     Bala  30000         Medium
2  Charlie  15000            Low

In [ ]:
#CREATE A COLUMN CALLED Double_sales USING lambda WITH APPLY FUNCTION
#Apply on specific column

df["Double_sales"]=df["Sales"].apply(lambda x:x*2)
df

  Customer  Sales sales_category  Double_sales
0     Asha  50000           High        100000
1     Bala  30000         Medium         60000
2  Charlie  15000            Low         30000

In [16]:
#Apply on entire dataframe
df.apply(lambda x:x*2)

         Customer   Sales sales_category  Double_sales
0        AshaAsha  100000       HighHigh        200000
1        BalaBala   60000   MediumMedium        120000
2  CharlieCharlie   30000         LowLow         60000

In [ ]:
#Apply with axis

#Axis =0        operate on columns
#Axis =1        operate on rows

df.apply(np.sum,axis=0)
#Calculates the sum cloumn-wise

Customer    AshaBalaCharlie
Sales                 95000
dtype: object

In [ ]:
data={
    "A":[10,20,30,40],
    "B":[1,2,3,4]
}

df=pd.DataFrame(data)
df

    A  B
0  10  1
1  20  2
2  30  3
3  40  4

In [11]:
#Row wise calculation or operation
df.apply(lambda row:row["A"] + row["B"],axis=1)

0    11
1    22
2    33
3    44
dtype: int64

In [20]:
data={"Revenue":[50000,30000],
       "Cost":[20000,15000]}

df=pd.DataFrame(data)

In [23]:
df["Profit"]=df.apply(lambda row:row["Revenue"]-row["Cost"],axis=1)
df

   Revenue   Cost  Profit
0    10000  20000  -10000
1        0  15000  -15000

In [25]:
import pandas as pd
import numpy as np

data={"Customer":["Asha","Bala","Charlie"],
      "Sales":["50000","30000","15000"]}

df=pd.DataFrame(data)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Customer  3 non-null      str
 1   Sales     3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [27]:
#astype - type conversion
#Example: sometimes numbers might be stored as strings

df["Sales"]=df["Sales"].astype(int)
df.info()

#Converting sales value datatype to numeric

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Customer  3 non-null      str
 1   Sales     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [ ]:
data={"Customer":["Asha","Bala","Charlie"],
      "Sales":["50000","30000","missing"]}

df=pd.DataFrame(data)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Customer  3 non-null      str
 1   Sales     3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [ ]:
#Any missing values will be replaced with NaN - coerce
pd.to_numeric(df["Sales"],errors="coerce")

0    50000.0
1    30000.0
2        NaN
Name: Sales, dtype: float64

.apply IS A LAST OPTION OR LAST RESORT BECAUSE .apply RUNS PYTHON LOOPS INTERNALLY

THIS IS NOT USEFUL WHEN THERE ARE MILLIONS OF ROWS
IN THIS CASE WE WOULD PREFER VECTORIZATION (NUMPY VECTORIZATION)

NUMPY VECTORIZATION IS FASTER.